<?php

use Illuminate\Database\Seeder;

class FatcomDataTypesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_types')->delete();
        
        \DB::table('data_types')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'users',
                'slug' => 'users',
                'display_name_singular' => 'User',
                'display_name_plural' => 'Users',
                'icon' => 'voyager-person',
                'model_name' => 'TCG\\Voyager\\Models\\User',
                'policy_name' => 'TCG\\Voyager\\Policies\\UserPolicy',
                'controller' => 'TCG\\Voyager\\Http\\Controllers\\VoyagerUserController',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":"id","order_display_column":"name","order_direction":"desc","default_search_key":"name","scope":null}',
                'created_at' => '2019-05-13 22:44:09',
                'updated_at' => '2019-10-24 21:04:39',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'menus',
                'slug' => 'menus',
                'display_name_singular' => 'Menu',
                'display_name_plural' => 'Menus',
                'icon' => 'voyager-list',
                'model_name' => 'TCG\\Voyager\\Models\\Menu',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2019-05-13 22:44:09',
                'updated_at' => '2019-05-13 22:44:09',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'roles',
                'slug' => 'roles',
                'display_name_singular' => 'Role',
                'display_name_plural' => 'Roles',
                'icon' => 'voyager-lock',
                'model_name' => 'TCG\\Voyager\\Models\\Role',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":"id","order_display_column":"name","order_direction":"desc","default_search_key":"name","scope":null}',
                'created_at' => '2019-05-13 22:44:09',
                'updated_at' => '2019-06-04 22:37:09',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'categories',
                'slug' => 'categories',
                'display_name_singular' => 'Category',
                'display_name_plural' => 'Categories',
                'icon' => 'voyager-categories',
                'model_name' => 'TCG\\Voyager\\Models\\Category',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2019-05-13 22:44:32',
                'updated_at' => '2019-05-13 22:44:32',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'posts',
                'slug' => 'posts',
                'display_name_singular' => 'Post',
                'display_name_plural' => 'Posts',
                'icon' => 'voyager-news',
                'model_name' => 'TCG\\Voyager\\Models\\Post',
                'policy_name' => 'TCG\\Voyager\\Policies\\PostPolicy',
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2019-05-13 22:44:34',
                'updated_at' => '2019-05-13 22:44:34',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'pages',
                'slug' => 'pages',
                'display_name_singular' => 'Page',
                'display_name_plural' => 'Pages',
                'icon' => 'voyager-file-text',
                'model_name' => 'TCG\\Voyager\\Models\\Page',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2019-05-13 22:44:37',
                'updated_at' => '2019-05-13 22:44:37',
            ),
            6 => 
            array (
                'id' => 11,
                'name' => 'permissions',
                'slug' => 'permissions',
                'display_name_singular' => 'Permiso',
                'display_name_plural' => 'Permisos',
                'icon' => 'voyager-certificate',
                'model_name' => 'App\\Permission',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-05-14 00:22:03',
                'updated_at' => '2019-08-10 21:05:46',
            ),
            7 => 
            array (
                'id' => 15,
                'name' => 'categorias',
                'slug' => 'categorias',
                'display_name_singular' => 'Categoría',
                'display_name_plural' => 'Categorías',
                'icon' => 'voyager-params',
                'model_name' => 'App\\Categoria',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-05-18 18:42:50',
                'updated_at' => '2019-10-30 14:44:26',
            ),
            8 => 
            array (
                'id' => 17,
                'name' => 'unidades',
                'slug' => 'unidades',
                'display_name_singular' => 'Unidad',
                'display_name_plural' => 'Unidades',
                'icon' => 'voyager-bar-chart',
                'model_name' => 'App\\Unidade',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-05-20 18:15:00',
                'updated_at' => '2019-05-23 14:44:31',
            ),
            9 => 
            array (
                'id' => 18,
                'name' => 'marcas',
                'slug' => 'marcas',
                'display_name_singular' => 'Marca',
                'display_name_plural' => 'Marcas',
                'icon' => 'voyager-tag',
                'model_name' => 'App\\Marca',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-05-20 18:21:55',
                'updated_at' => '2019-05-20 18:22:52',
            ),
            10 => 
            array (
                'id' => 19,
                'name' => 'tallas',
                'slug' => 'tallas',
                'display_name_singular' => 'Talla',
                'display_name_plural' => 'Tallas',
                'icon' => 'voyager-ticket',
                'model_name' => 'App\\Talla',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-05-20 18:26:55',
                'updated_at' => '2019-09-06 22:59:00',
            ),
            11 => 
            array (
                'id' => 20,
                'name' => 'tamanios',
                'slug' => 'tamanios',
                'display_name_singular' => 'Tamaño',
                'display_name_plural' => 'Tamaños',
                'icon' => 'voyager-resize-full',
                'model_name' => 'App\\Tamanio',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-05-20 18:28:39',
                'updated_at' => '2019-05-23 14:46:20',
            ),
            12 => 
            array (
                'id' => 21,
                'name' => 'colores',
                'slug' => 'colores',
                'display_name_singular' => 'Color',
                'display_name_plural' => 'Colores',
                'icon' => 'voyager-paint-bucket',
                'model_name' => 'App\\Colore',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-05-20 18:35:23',
                'updated_at' => '2019-05-23 14:48:20',
            ),
            13 => 
            array (
                'id' => 22,
                'name' => 'generos',
                'slug' => 'generos',
                'display_name_singular' => 'Genero',
                'display_name_plural' => 'Generos',
                'icon' => 'voyager-params',
                'model_name' => 'App\\Genero',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-05-20 18:59:35',
                'updated_at' => '2019-05-20 19:01:12',
            ),
            14 => 
            array (
                'id' => 23,
                'name' => 'usos',
                'slug' => 'usos',
                'display_name_singular' => 'Uso',
                'display_name_plural' => 'Usos',
                'icon' => 'voyager-lightbulb',
                'model_name' => 'App\\Uso',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-05-20 21:02:15',
                'updated_at' => '2019-05-23 14:49:05',
            ),
            15 => 
            array (
                'id' => 25,
                'name' => 'monedas',
                'slug' => 'monedas',
                'display_name_singular' => 'Moneda',
                'display_name_plural' => 'Monedas',
                'icon' => 'voyager-dollar',
                'model_name' => 'App\\Moneda',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-05-22 22:29:40',
                'updated_at' => '2019-05-22 22:31:44',
            ),
            16 => 
            array (
                'id' => 27,
                'name' => 'insumos',
                'slug' => 'insumos',
                'display_name_singular' => 'Insumo',
                'display_name_plural' => 'Insumos',
                'icon' => 'voyager-params',
                'model_name' => 'App\\Insumo',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-06-14 21:19:56',
                'updated_at' => '2019-08-14 17:34:24',
            ),
            17 => 
            array (
                'id' => 29,
                'name' => 'proveedores',
                'slug' => 'proveedores',
                'display_name_singular' => 'Proveedor',
                'display_name_plural' => 'Proveedores',
                'icon' => 'voyager-people',
                'model_name' => 'App\\Proveedore',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-06-18 21:31:59',
                'updated_at' => '2019-06-18 21:39:03',
            ),
            18 => 
            array (
                'id' => 32,
                'name' => 'pasarela_pagos',
                'slug' => 'pasarela-pagos',
                'display_name_singular' => 'Pasarelas de  Pago',
                'display_name_plural' => 'Pasarela de Pagos',
                'icon' => 'voyager-logbook',
                'model_name' => 'App\\PasarelaPago',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-06-20 22:23:34',
                'updated_at' => '2019-06-20 22:54:16',
            ),
            19 => 
            array (
                'id' => 33,
                'name' => 'ventas_estados',
                'slug' => 'ventas-estados',
                'display_name_singular' => 'Estado de venta',
                'display_name_plural' => 'Estados de la venta',
                'icon' => 'voyager-info-circled',
                'model_name' => 'App\\VentasEstado',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":"id","order_display_column":"id","order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-07-13 15:11:40',
                'updated_at' => '2019-11-27 20:07:13',
            ),
            20 => 
            array (
                'id' => 34,
                'name' => 'ventas_tipos',
                'slug' => 'ventas-tipos',
                'display_name_singular' => 'Tipo de ventas',
                'display_name_plural' => 'Tipos de venta',
                'icon' => 'voyager-params',
                'model_name' => 'App\\VentasTipo',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-07-24 21:54:55',
                'updated_at' => '2019-07-24 22:12:03',
            ),
            21 => 
            array (
                'id' => 35,
                'name' => 'ventas_detalle_tipo_estados',
                'slug' => 'ventas-detalle-tipo-estados',
                'display_name_singular' => 'Estado de tipos de venta',
                'display_name_plural' => 'Estados de tipos de venta',
                'icon' => 'voyager-forward',
                'model_name' => 'App\\VentasDetalleTipoEstado',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":"id","order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-07-24 22:01:58',
                'updated_at' => '2019-07-24 22:22:16',
            ),
            22 => 
            array (
                'id' => 37,
                'name' => 'localidades',
                'slug' => 'localidades',
                'display_name_singular' => 'Localidade',
                'display_name_plural' => 'Localidades',
                'icon' => 'voyager-location',
                'model_name' => 'App\\Localidade',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-08-15 21:42:31',
                'updated_at' => '2019-08-15 21:45:02',
            ),
            23 => 
            array (
                'id' => 39,
                'name' => 'subcategorias',
                'slug' => 'subcategorias',
                'display_name_singular' => 'Subcategoria',
                'display_name_plural' => 'Subcategorias',
                'icon' => 'voyager-list-add',
                'model_name' => 'App\\Subcategoria',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-10-30 15:15:22',
                'updated_at' => '2019-10-30 17:32:05',
            ),
            24 => 
            array (
                'id' => 44,
                'name' => 'publicaciones',
                'slug' => 'publicaciones',
                'display_name_singular' => 'Publicacione',
                'display_name_plural' => 'Publicaciones',
                'icon' => 'voyager-news',
                'model_name' => 'App\\Publicacione',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-11-29 17:30:44',
                'updated_at' => '2019-11-30 16:34:25',
            ),
            25 => 
            array (
                'id' => 45,
                'name' => 'extras',
                'slug' => 'extras',
                'display_name_singular' => 'Extra',
                'display_name_plural' => 'Extras',
                'icon' => 'voyager-list-add',
                'model_name' => 'App\\Extra',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-02-18 17:04:55',
                'updated_at' => '2020-02-18 18:29:11',
            ),
        ));
        
        
    }
}